version: "2.4"
volumes:
  dbdata:
services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: php-app-docker:latest
    depends_on:
      database:
        condition: service_healthy
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
      PHP_ENV: ${PHP_ENV}
    working_dir: /var/www/application
    volumes:
      - ./application:/var/www/application
    ports:
      - ${APP_PORT}:8080
  database:
    image: postgres:12.3
    restart: on-failure
    healthcheck:
      test: pg_isready -h 127.0.0.1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
